# Generated by Django 4.0 on 2023-05-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre y Apellido:')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('contacto_tipo', models.IntegerField(choices=[[0, 'Pedir informacion'], [1, 'Mandar una queja'], [3, 'Sugerir, recomendar']], default=[0, 'Pedir informacion'], verbose_name='Tipo de Contacto')),
                ('subscripcion', models.BooleanField(default=False, verbose_name='Recibir correos de productos e informacion')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envio')),
            ],
        ),
    ]
