# Generated by Django 4.0 on 2023-05-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='uploads/categorias/img_defecto_hhgi4q.jpg', upload_to='uploads/categorias/', verbose_name='Imagen de categoria'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='uploads/products/img_defecto_p_fugbfc.jpg', upload_to='uploads/products/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(default='uploads/uploads/users/img_defecto_u_ruk6ou.jpg', upload_to='uploads/users/', verbose_name='imagen de perfil'),
        ),
    ]
