# Generated by Django 4.0 on 2023-05-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_image_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(default='uploads/users/img_defecto_u_ruk6ou.jpg', upload_to='uploads/users/', verbose_name='imagen de perfil'),
        ),
    ]
