# Generated by Django 4.0 on 2023-05-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='uploads/categorias/img_defecto_hhgi4q.jpg', upload_to='media/uploads/categorias/', verbose_name='Imagen de categoria'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='uploads/products/img_defecto_p_fugbfc.jpg', upload_to='media/uploads/products/', verbose_name='Imagen de producto'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(default='uploads/users/img_defecto_u_ruk6ou.jpg', upload_to='media/uploads/users/', verbose_name='Imagen de perfil'),
        ),
    ]
