# Generated by Django 4.0 on 2023-05-31 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_category_image_alter_product_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('cliente', 'Cliente'), ('emprendedor', 'Emprendedor'), ('todoenuno', 'TodoEnUno')], max_length=20)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='rol',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.rol'),
        ),
    ]
