# Generated by Django 4.0 on 2023-05-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rol_customer_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('emprendedor', 'Emprendedor'), ('todoenuno', 'TodoEnUno')], default='cliente', max_length=20),
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
