# Generated by Django 4.0 on 2023-05-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='img',
            field=models.ImageField(default='categorias/img_defecto_zstoxl.jpg', upload_to='categorias/', verbose_name='Imagen de categoria'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='img',
            field=models.ImageField(default='productos/img_defecto_cpzv2f.jpg', upload_to='productos/', verbose_name='Imagen de producto'),
        ),
    ]
