# Generated by Django 4.1.7 on 2023-03-28 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_representante', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('rubro', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('NIT', models.IntegerField()),
                ('password', models.CharField(help_text='Introduce tu contraseña', max_length=10)),
                ('correo', models.EmailField(max_length=254)),
                ('banco', models.CharField(max_length=100)),
                ('img_perfil', models.ImageField(default='img_default', upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='project',
        ),
        migrations.AddField(
            model_name='emprendedor',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.usuario'),
        ),
    ]
