# Generated by Django 4.1.7 on 2023-03-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(help_text='Introduce tu nombre completo', max_length=200)),
                ('nit', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('banco', models.CharField(max_length=20)),
                ('img_perfil', models.ImageField(default='default.png', upload_to='')),
                ('fecha_nacimiento', models.DateTimeField(blank=True)),
            ],
        ),
    ]
