# Generated by Django 4.1.7 on 2023-03-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_emprendedor_usuario_delete_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nombre_completo',
            field=models.CharField(help_text='Introduce tu nombre completo', max_length=200),
        ),
    ]
