# Generated by Django 4.1.7 on 2023-03-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_alter_usuario_nombre_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='img_perfil',
            field=models.ImageField(default='img_default.png', upload_to=''),
        ),
    ]
