# Generated by Django 4.1.7 on 2023-03-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_alter_consumidor_img_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumidor',
            name='img_perfil',
            field=models.ImageField(null=True, upload_to='consumidores'),
        ),
        migrations.AlterField(
            model_name='emprendedor',
            name='img_perfil',
            field=models.ImageField(null=True, upload_to='consumidores'),
        ),
    ]
