# Generated by Django 4.1.7 on 2023-03-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0006_alter_consumidor_img_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprendedor',
            name='img_perfil',
            field=models.ImageField(null=True, upload_to='emprendedores'),
        ),
    ]
