# Generated by Django 4.1.7 on 2023-04-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0009_alter_consumidor_img_perfil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=100)),
                ('img_categoria', models.ImageField(null=True, upload_to='categoria/')),
            ],
        ),
    ]
