# Generated by Django 4.1.7 on 2023-04-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0010_categorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propietarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('num_telefono', models.IntegerField(max_length=10)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('cargo', models.CharField(max_length=100)),
                ('img', models.ImageField(null=True, upload_to='Propietarios/')),
            ],
        ),
    ]
