# Generated by Django 4.1.7 on 2023-04-10 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0011_propietarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propietarios',
            name='num_telefono',
        ),
    ]
