# Generated by Django 4.1.7 on 2023-04-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0014_remove_propietarios_numtelefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='propietarios',
            name='numTelefono',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
