# Generated by Django 4.1.7 on 2023-04-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0015_propietarios_numtelefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=200)),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('descuento', models.CharField(max_length=5)),
                ('img_producto', models.ImageField(null=True, upload_to='Productos/')),
            ],
        ),
    ]
